export default {

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api-reference' }],
    },
  ],
  mySidebar: [
    {
      type: 'doc',
      id: 'intro', // This links to intro.md
      label: 'Getting Started with API',
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/authentication',
        'api-reference/errors',
      ],
    },
    {
      type: 'doc',
      id: 'changelog', // This links to changelog.md
      label: 'Changelog',
    },
  ],
};